import Phaser from 'phaser';
import { SceneRouter } from '@scenes/SceneRouter';
import { SceneKey } from '@scenes/scene-keys';

export class BootScene extends Phaser.Scene {
  constructor() {
    super({ key: SceneKey.Boot });
  }

  preload(): void {
    // Load the asset manifest generated by scripts/generate-atlas.js.
    // If the file is missing (dev without running the script), PreloadScene
    // falls back to its original hardcoded asset list.
    this.load.json('asset-manifest', 'assets/asset-manifest.json');
  }

  create(): void {
    const manifest = this.cache.json.get('asset-manifest') ?? null;
    SceneRouter.for(this).start(SceneKey.Preload, { manifest });
  }
}
