/** BGM track keys — must match asset filenames loaded in PreloadScene. */
export const BGM = {
  TITLE:          'bgm-title',
  PALLET_TOWN:    'bgm-pallet-town',
  ROUTE:          'bgm-route',
  BATTLE_WILD:    'bgm-battle-wild',
  BATTLE_TRAINER: 'bgm-battle-trainer',
  BATTLE_GYM:     'bgm-battle-gym',
  VICTORY:        'bgm-victory',
  POKEMON_CENTER: 'bgm-pokemon-center',
  RIVAL_BATTLE:     'bgm-rival-battle',
  GYM_LEADER_BATTLE:'bgm-gym-leader-battle',
  LEGENDARY:        'bgm-legendary',
  EVOLUTION:        'bgm-evolution',
  VILLAIN:          'bgm-villain',
  VICTORY_ROAD:     'bgm-victory-road',
  CREDITS:          'bgm-credits',
  CORAL_HARBOR:     'bgm-coral-harbor',
  IRONVALE:         'bgm-ironvale',
  VOLTARA:          'bgm-voltara',
  WRAITHMOOR:       'bgm-wraithmoor',
  SCALECREST:       'bgm-scalecrest',
  CINDERFALL:       'bgm-cinderfall',
  DUNGEON:          'bgm-dungeon',
  BATTLE_RIVAL:     'bgm-battle-rival',
  BATTLE_LEGENDARY: 'bgm-battle-legendary',
  BATTLE_VILLAIN:   'bgm-battle-villain',
  TOWN_GENERIC:     'bgm-town-generic',
  TOWN_COASTAL:     'bgm-town-coastal',
  TOWN_MOUNTAIN:    'bgm-town-mountain',
  TOWN_SPOOKY:      'bgm-town-spooky',
  TOWN_INDUSTRIAL:  'bgm-town-industrial',
  CAVE:             'bgm-cave',
  VILLAIN_LAIR:     'bgm-villain-lair',
} as const;

/** SFX keys — must match asset filenames loaded in PreloadScene. */
export const SFX = {
  // Menu
  CURSOR:     'sfx-cursor',
  CONFIRM:    'sfx-confirm',
  CANCEL:     'sfx-cancel',
  ERROR:      'sfx-error',

  // Battle
  HIT_NORMAL:       'sfx-hit-normal',
  HIT_SUPER:        'sfx-hit-super',
  HIT_WEAK:         'sfx-hit-weak',
  HIT_CRIT:         'sfx-hit-crit',
  FAINT:            'sfx-faint',
  BALL_THROW:       'sfx-ball-throw',
  BALL_SHAKE:       'sfx-ball-shake',
  CATCH_SUCCESS:    'sfx-catch-success',
  EXP_FILL:         'sfx-exp-fill',
  LEVEL_UP:         'sfx-level-up',

  // Additional Battle
  STAT_UP:          'sfx-stat-up',
  STAT_DOWN:        'sfx-stat-down',
  RUN_SUCCESS:      'sfx-run-success',
  RUN_FAIL:         'sfx-run-fail',
  LOW_HP:           'sfx-low-hp',

  // Overworld
  DOOR_OPEN:    'sfx-door-open',
  LEDGE_JUMP:   'sfx-ledge-jump',
  BUMP:         'sfx-bump',
  ENCOUNTER:    'sfx-encounter',

  // Overworld / UI
  ITEM_PICKUP:      'sfx-item-pickup',
  BADGE_FANFARE:    'sfx-badge-fanfare',
  HEAL_JINGLE:      'sfx-heal-jingle',
  DOOR_CLOSE:       'sfx-door-close',
  SAVE:             'sfx-save',
  PC_ON:            'sfx-pc-on',
  PC_OFF:           'sfx-pc-off',

  // Battle effects
  STAT_RAISE:       'sfx-stat-raise',
  STAT_LOWER:       'sfx-stat-lower',
  STATUS_INFLICT:   'sfx-status-inflict',
  SYNTHESIS_ACTIVATE: 'sfx-synthesis-activate',

  // Menu / UI
  ITEM_OBTAIN:      'sfx-item-obtain',
  BADGE_GET:        'sfx-badge-get',
  POKEDEX_REGISTER: 'sfx-pokedex-register',

  // Overworld footsteps
  FOOTSTEP_GRASS:   'sfx-footstep-grass',
  FOOTSTEP_SAND:    'sfx-footstep-sand',
  FOOTSTEP_STONE:   'sfx-footstep-stone',
  FOOTSTEP_WOOD:    'sfx-footstep-wood',
  WATER_SPLASH:     'sfx-water-splash',
  FOOTSTEP_METAL:   'sfx-footstep-metal',
} as const;

/** Map key → BGM key mapping. */
export const MAP_BGM: Record<string, string> = {
  'pallet-town':         BGM.PALLET_TOWN,
  'route-1':             BGM.ROUTE,
  'route-2':             BGM.ROUTE,
  'viridian-city':       BGM.PALLET_TOWN,
  'viridian-forest':     BGM.ROUTE,
  'pewter-city':         BGM.PALLET_TOWN,
  // Interiors
  'pallet-player-house': BGM.PALLET_TOWN,
  'pallet-rival-house':  BGM.PALLET_TOWN,
  'pallet-oak-lab':      BGM.PALLET_TOWN,
  'viridian-pokecenter':  BGM.POKEMON_CENTER,
  'viridian-pokemart':    BGM.PALLET_TOWN,
  'pewter-pokecenter':    BGM.POKEMON_CENTER,
  'pewter-gym':           BGM.BATTLE_GYM,
  'pewter-museum':        BGM.PALLET_TOWN,
  'crystal-cavern':        BGM.CAVE,
  'route-3':               BGM.ROUTE,
  'coral-harbor':          BGM.TOWN_COASTAL,
  'coral-pokecenter':      BGM.POKEMON_CENTER,
  'coral-pokemart':        BGM.TOWN_COASTAL,
  'coral-gym':             BGM.BATTLE_GYM,
  'route-4':               BGM.ROUTE,
  'ember-mines':           BGM.CAVE,
  'ironvale-city':         BGM.TOWN_COASTAL,
  'ironvale-pokecenter':   BGM.POKEMON_CENTER,
  'ironvale-pokemart':     BGM.TOWN_COASTAL,
  'ironvale-gym':          BGM.BATTLE_GYM,
  'route-5':               BGM.ROUTE,
  'verdantia-village':     BGM.PALLET_TOWN,
  'verdantia-pokecenter':  BGM.POKEMON_CENTER,
  'verdantia-pokemart':    BGM.PALLET_TOWN,
  'verdantia-gym':         BGM.BATTLE_GYM,
  'voltara-city':          BGM.TOWN_INDUSTRIAL,
  'voltara-pokecenter':    BGM.POKEMON_CENTER,
  'voltara-pokemart':      BGM.TOWN_INDUSTRIAL,
  'voltara-gym':           BGM.BATTLE_GYM,
  // Act 3
  'route-6':               BGM.ROUTE,
  'wraithmoor-town':       BGM.TOWN_SPOOKY,
  'wraithmoor-pokecenter': BGM.POKEMON_CENTER,
  'wraithmoor-pokemart':   BGM.TOWN_SPOOKY,
  'wraithmoor-gym':        BGM.BATTLE_GYM,
  'route-7':               BGM.ROUTE,
  'scalecrest-citadel':    BGM.TOWN_MOUNTAIN,
  'scalecrest-pokecenter': BGM.POKEMON_CENTER,
  'scalecrest-pokemart':   BGM.TOWN_MOUNTAIN,
  'scalecrest-gym':        BGM.BATTLE_GYM,
  'cinderfall-town':       BGM.TOWN_INDUSTRIAL,
  'cinderfall-pokecenter': BGM.POKEMON_CENTER,
  'cinderfall-pokemart':   BGM.TOWN_INDUSTRIAL,
  'cinderfall-gym':        BGM.BATTLE_GYM,
  // Act 4
  'victory-road':          BGM.VICTORY_ROAD,
  'pokemon-league':        BGM.BATTLE_GYM,
};
